# Generated by Django 6.1 on 2026-09-12 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sucursales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id_insumo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('unidad_medida', models.CharField(max_length=20)),
                ('estado', models.CharField(default='activo', max_length=20)),
            ],
            options={
                'db_table': 'insumo',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('precio', models.FloatField()),
                ('estado', models.CharField(default='activo', max_length=20)),
            ],
            options={
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('correo', models.CharField(blank=True, max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('estado', models.CharField(default='activo', max_length=20)),
            ],
            options={
                'db_table': 'proveedor',
            },
        ),
        migrations.CreateModel(
            name='InsumoSucursal',
            fields=[
                ('pk', models.CompositePrimaryKey('insumo', 'sucursal', blank=True, editable=False, primary_key=True, serialize=False)),
                ('stock', models.FloatField(default=0)),
                ('insumo', models.ForeignKey(db_column='id_insumo', on_delete=django.db.models.deletion.CASCADE, related_name='stock_sucursales', to='productos.insumo')),
                ('sucursal', models.ForeignKey(db_column='id_sucursal', on_delete=django.db.models.deletion.CASCADE, related_name='stock_insumos', to='sucursales.sucursal')),
            ],
            options={
                'db_table': 'insumo_sucursal',
            },
        ),
        migrations.CreateModel(
            name='ProductoInsumo',
            fields=[
                ('pk', models.CompositePrimaryKey('producto', 'insumo', blank=True, editable=False, primary_key=True, serialize=False)),
                ('cantidad_requerida', models.FloatField()),
                ('insumo', models.ForeignKey(db_column='id_insumo', on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='productos.insumo')),
                ('producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='productos.producto')),
            ],
            options={
                'db_table': 'producto_insumo',
            },
        ),
        migrations.CreateModel(
            name='ProductoSucursal',
            fields=[
                ('pk', models.CompositePrimaryKey('producto', 'sucursal', blank=True, editable=False, primary_key=True, serialize=False)),
                ('stock', models.IntegerField(default=0)),
                ('producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, related_name='stock_sucursales', to='productos.producto')),
                ('sucursal', models.ForeignKey(db_column='id_sucursal', on_delete=django.db.models.deletion.CASCADE, related_name='stock_productos', to='sucursales.sucursal')),
            ],
            options={
                'db_table': 'producto_sucursal',
            },
        ),
        migrations.CreateModel(
            name='ProveedorInsumo',
            fields=[
                ('pk', models.CompositePrimaryKey('proveedor', 'insumo', blank=True, editable=False, primary_key=True, serialize=False)),
                ('costo', models.FloatField()),
                ('insumo', models.ForeignKey(db_column='id_insumo', on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to='productos.insumo')),
                ('proveedor', models.ForeignKey(db_column='id_proveedor', on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='productos.proveedor')),
            ],
            options={
                'db_table': 'proveedor_insumo',
            },
        ),
    ]
