# Generated by Django 6.1 on 2026-09-12 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='proveedor_principal',
            field=models.ForeignKey(blank=True, db_column='id_proveedor_principal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insumos_principales', to='productos.proveedor'),
        ),
        migrations.AddField(
            model_name='insumosucursal',
            name='stock_minimo',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='productosucursal',
            name='stock_minimo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='insumo_principal',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='proxima_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='urgente',
            field=models.BooleanField(default=False),
        ),
    ]
