# Generated by Django 6.1 on 2026-09-12 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_insumo_proveedor_principal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='urgente',
        ),
    ]
