# Generated by Django 6.1 on 2026-09-12 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id_devolucion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('monto', models.FloatField()),
            ],
            options={
                'db_table': 'devolucion',
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id_insumo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('unidad_medida', models.CharField(max_length=20)),
                ('estado', models.CharField(default='activo', max_length=20)),
            ],
            options={
                'db_table': 'insumo',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('precio', models.FloatField()),
                ('estado', models.CharField(default='activo', max_length=20)),
            ],
            options={
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('correo', models.CharField(blank=True, max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('estado', models.CharField(default='activo', max_length=20)),
            ],
            options={
                'db_table': 'proveedor',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id_sucursal', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('estado', models.CharField(default='activo', max_length=20)),
            ],
            options={
                'db_table': 'sucursal',
            },
        ),
        migrations.CreateModel(
            name='ProductoInsumo',
            fields=[
                ('pk', models.CompositePrimaryKey('producto', 'insumo', blank=True, editable=False, primary_key=True, serialize=False)),
                ('cantidad_requerida', models.FloatField()),
                ('insumo', models.ForeignKey(db_column='id_insumo', on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='core.insumo')),
                ('producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='core.producto')),
            ],
            options={
                'db_table': 'producto_insumo',
            },
        ),
        migrations.CreateModel(
            name='ProveedorInsumo',
            fields=[
                ('pk', models.CompositePrimaryKey('proveedor', 'insumo', blank=True, editable=False, primary_key=True, serialize=False)),
                ('costo', models.FloatField()),
                ('insumo', models.ForeignKey(db_column='id_insumo', on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to='core.insumo')),
                ('proveedor', models.ForeignKey(db_column='id_proveedor', on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='core.proveedor')),
            ],
            options={
                'db_table': 'proveedor_insumo',
            },
        ),
        migrations.CreateModel(
            name='ProductoSucursal',
            fields=[
                ('pk', models.CompositePrimaryKey('producto', 'sucursal', blank=True, editable=False, primary_key=True, serialize=False)),
                ('stock', models.IntegerField(default=0)),
                ('producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, related_name='stock_sucursales', to='core.producto')),
                ('sucursal', models.ForeignKey(db_column='id_sucursal', on_delete=django.db.models.deletion.CASCADE, related_name='stock_productos', to='core.sucursal')),
            ],
            options={
                'db_table': 'producto_sucursal',
            },
        ),
        migrations.CreateModel(
            name='InsumoSucursal',
            fields=[
                ('pk', models.CompositePrimaryKey('insumo', 'sucursal', blank=True, editable=False, primary_key=True, serialize=False)),
                ('stock', models.FloatField(default=0)),
                ('insumo', models.ForeignKey(db_column='id_insumo', on_delete=django.db.models.deletion.CASCADE, related_name='stock_sucursales', to='core.insumo')),
                ('sucursal', models.ForeignKey(db_column='id_sucursal', on_delete=django.db.models.deletion.CASCADE, related_name='stock_insumos', to='core.sucursal')),
            ],
            options={
                'db_table': 'insumo_sucursal',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('correo', models.CharField(max_length=150, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('fecha_ingreso', models.DateField()),
                ('estado', models.CharField(default='activo', max_length=20)),
                ('rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='core.rol')),
                ('sucursal', models.ForeignKey(db_column='id_sucursal', on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='core.sucursal')),
            ],
            options={
                'db_table': 'empleado',
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id_turno', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('estado', models.CharField(default='abierto', max_length=20)),
                ('monto_inicial', models.FloatField(default=0)),
                ('monto_esperado', models.FloatField(blank=True, null=True)),
                ('monto_contado', models.FloatField(blank=True, null=True)),
                ('diferencia', models.FloatField(blank=True, null=True)),
                ('empleado', models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='core.empleado')),
                ('sucursal', models.ForeignKey(db_column='id_sucursal', on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='core.sucursal')),
            ],
            options={
                'db_table': 'turno',
            },
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id_movimiento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=20)),
                ('monto', models.FloatField()),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('fecha_hora', models.DateTimeField()),
                ('turno', models.ForeignKey(db_column='id_turno', on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_caja', to='core.turno')),
            ],
            options={
                'db_table': 'movimiento_caja',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('subtotal', models.FloatField()),
                ('impuesto', models.FloatField(default=0)),
                ('total', models.FloatField()),
                ('estado', models.CharField(default='completada', max_length=20)),
                ('turno', models.ForeignKey(db_column='id_turno', on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='core.turno')),
            ],
            options={
                'db_table': 'venta',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('metodo_pago', models.CharField(max_length=30)),
                ('monto', models.FloatField()),
                ('fecha', models.DateField()),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('venta', models.ForeignKey(db_column='id_venta', on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='core.venta')),
            ],
            options={
                'db_table': 'pago',
            },
        ),
        migrations.CreateModel(
            name='DevolucionDetalle',
            fields=[
                ('pk', models.CompositePrimaryKey('devolucion', 'venta', 'producto', blank=True, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('devolucion', models.ForeignKey(db_column='id_devolucion', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.devolucion')),
                ('producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.PROTECT, related_name='detalles_devolucion', to='core.producto')),
                ('venta', models.ForeignKey(db_column='id_venta', on_delete=django.db.models.deletion.CASCADE, related_name='detalles_devolucion', to='core.venta')),
            ],
            options={
                'db_table': 'devolucion_detalle',
            },
        ),
        migrations.AddField(
            model_name='devolucion',
            name='venta',
            field=models.ForeignKey(db_column='id_venta', on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones', to='core.venta'),
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('pk', models.CompositePrimaryKey('venta', 'producto', blank=True, editable=False, primary_key=True, serialize=False)),
                ('unidades', models.IntegerField()),
                ('precio_unitario', models.FloatField()),
                ('subtotal', models.FloatField()),
                ('producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.PROTECT, related_name='detalles_venta', to='core.producto')),
                ('venta', models.ForeignKey(db_column='id_venta', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.venta')),
            ],
            options={
                'db_table': 'detalle_venta',
            },
        ),
    ]
