# Generated by Django 6.1 on 2026-09-12 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='fondo_caja_default',
            field=models.FloatField(default=500),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='hora_apertura',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='hora_cierre',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
