# Generated by Django 6.1 on 2026-09-12 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='numero_empleado',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
