# Generated by Django 6.1 on 2026-09-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_empleado_numero_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='horario_dias',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='empleado',
            name='horario_hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='horario_hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
