# Generated by Django 6.1 on 2026-09-12 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0001_initial'),
        ('productos', '0001_initial'),
        ('sucursales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id_devolucion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('monto', models.FloatField()),
            ],
            options={
                'db_table': 'devolucion',
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id_turno', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('estado', models.CharField(default='abierto', max_length=20)),
                ('monto_inicial', models.FloatField(default=0)),
                ('monto_esperado', models.FloatField(blank=True, null=True)),
                ('monto_contado', models.FloatField(blank=True, null=True)),
                ('diferencia', models.FloatField(blank=True, null=True)),
                ('empleado', models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='empleados.empleado')),
                ('sucursal', models.ForeignKey(db_column='id_sucursal', on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='sucursales.sucursal')),
            ],
            options={
                'db_table': 'turno',
            },
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id_movimiento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=20)),
                ('monto', models.FloatField()),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('fecha_hora', models.DateTimeField()),
                ('turno', models.ForeignKey(db_column='id_turno', on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_caja', to='ventas.turno')),
            ],
            options={
                'db_table': 'movimiento_caja',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('subtotal', models.FloatField()),
                ('impuesto', models.FloatField(default=0)),
                ('total', models.FloatField()),
                ('estado', models.CharField(default='completada', max_length=20)),
                ('turno', models.ForeignKey(db_column='id_turno', on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='ventas.turno')),
            ],
            options={
                'db_table': 'venta',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('metodo_pago', models.CharField(max_length=30)),
                ('monto', models.FloatField()),
                ('fecha', models.DateField()),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('venta', models.ForeignKey(db_column='id_venta', on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='ventas.venta')),
            ],
            options={
                'db_table': 'pago',
            },
        ),
        migrations.CreateModel(
            name='DevolucionDetalle',
            fields=[
                ('pk', models.CompositePrimaryKey('devolucion', 'venta', 'producto', blank=True, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('devolucion', models.ForeignKey(db_column='id_devolucion', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.devolucion')),
                ('producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.PROTECT, related_name='detalles_devolucion', to='productos.producto')),
                ('venta', models.ForeignKey(db_column='id_venta', on_delete=django.db.models.deletion.CASCADE, related_name='detalles_devolucion', to='ventas.venta')),
            ],
            options={
                'db_table': 'devolucion_detalle',
            },
        ),
        migrations.AddField(
            model_name='devolucion',
            name='venta',
            field=models.ForeignKey(db_column='id_venta', on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones', to='ventas.venta'),
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('pk', models.CompositePrimaryKey('venta', 'producto', blank=True, editable=False, primary_key=True, serialize=False)),
                ('unidades', models.IntegerField()),
                ('precio_unitario', models.FloatField()),
                ('subtotal', models.FloatField()),
                ('producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.PROTECT, related_name='detalles_venta', to='productos.producto')),
                ('venta', models.ForeignKey(db_column='id_venta', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.venta')),
            ],
            options={
                'db_table': 'detalle_venta',
            },
        ),
    ]
