# Generated by Django 6.1 on 2026-09-12 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_venta_creado_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucion',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
