# Generated by Django 6.1 on 2026-09-12 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0002_empleado_numero_empleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(max_length=50)),
                ('detalle', models.CharField(max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(db_column='id_actor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_auditadas', to='empleados.empleado')),
            ],
            options={
                'db_table': 'registro_auditoria',
                'ordering': ['-creado_en'],
            },
        ),
    ]
